version: '2'

services:
    service_myadmin_db:
        container_name: service_myadmin_db
        image: mysql:5.7
        volumes:
            - ../env/d-mysql:/var/lib/mysql
        env_file:
            - ./.env

    service_myadmin_phpmyadmin:
        container_name: service_myadmin_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PHPMYADMIN_PORT}:80
        links:
            - service_myadmin_db:db
