version: '3'

services:
    service_mysql:
        restart: always
        container_name: service_mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ./d-mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=dbname
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        networks:
            - net_myadmin

    service_phpmyadmin:
        container_name: service_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 81:80
        links:
            - service_mysql:db
        networks:
            - net_myadmin
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root


networks:
    net_myadmin:
        driver: bridge
